CREATE TABLE IF NOT EXISTS demonstracao_contabel (
    id SERIAL PRIMARY KEY,
    "DATA" DATE NOT NULL,
    REG_ANS VARCHAR(6) NOT NULL CHECK (REG_ANS ~ '^[0-9]+$'),
    CD_CONTA_CONTABIL VARCHAR(9) CHECK (CD_CONTA_CONTABIL ~ '^[0-9]+$'),
    DESCRICAO VARCHAR(150) NOT NULL,
    VL_SALDO_INICIAL NUMERIC(15,2) NOT NULL,
    VL_SALDO_FINAL NUMERIC(15,2) NOT NULL
);
